"""Unified domain model for document parsing."""

from .models import (
    Block,
    BlockType,
    BoundingBox,
    CoordinateSystem,
    Diagnostic,
    DiagnosticSeverity,
    DocumentNode,
    DocumentTree,
    FigureData,
    FileIdentity,
    Page,
    SourceDocument,
    SourceMethod,
    SourceRef,
    TableCell,
    TableData,
    ImageAsset,
    TextSpan,
)

__all__ = [
    "Block",
    "BlockType",
    "BoundingBox",
    "CoordinateSystem",
    "Diagnostic",
    "DiagnosticSeverity",
    "DocumentNode",
    "DocumentTree",
    "FigureData",
    "ImageAsset",
    "FileIdentity",
    "Page",
    "SourceDocument",
    "SourceMethod",
    "SourceRef",
    "TableCell",
    "TableData",
    "TextSpan",
]
